from opencosmo.index import IndexArray

def take_chunked_from_chunked(
    start: IndexArray, size: IndexArray, take_start: IndexArray, take_size: IndexArray
) -> tuple[IndexArray, IndexArray]: ...
def get_simple_range(index: IndexArray) -> tuple[int, int]: ...
def get_chunked_range(start: IndexArray, size: IndexArray) -> tuple[int, int]: ...
def n_in_range_chunked(
    start: IndexArray, size: IndexArray, range_start: IndexArray, range_size: IndexArray
) -> IndexArray: ...
def chunked_into_array(start: IndexArray, size: IndexArray) -> IndexArray: ...
def take_chunked_from_simple(
    simple: IndexArray, start: IndexArray, size: IndexArray
) -> IndexArray: ...
